### ISSUE TITLE
Better handling of GIT conflict markers

### ISSUE THREAD

**Issue by blaqbern** [tonsky/FiraCode#234]
Conflict markers from GIT (=======, >>>>>>> and <<<<<<<) currently render somewhat  awkwardly: 

![screen shot 2016-07-30 at 11 40 09 am](https://cloud.githubusercontent.com/assets/10851286/17271479/eeea4cc4-564a-11e6-8215-26ff0f022c7d.png)

Might be nice to see ligatures for these, or just render them as vanilla Fira mono.

This is sort of similar to #229 

Awesome work on this project.

**Comment by tonsky** [comment]
That should be fixed in 1.200

**Comment by blaqbern** [comment]
Ah! I'm using an [Atom package](https://atom.io/packages/fonts) that bundles a bunch of monospaced fonts. Must be using an older version. Thanks again for the awesome.

**Comment by davmillar** [comment]
@tonsky it was not working in 1.200 for me. Updating to 1.204 has partially fixed the display, but the first two less-than symbols still look out of place.

![image](https://user-images.githubusercontent.com/576958/31616843-69bd815e-b253-11e7-8948-17a065a234f0.png)

**Comment by j-f1** [comment]
That’s probably because the syntax highlighter puts them in a separate element, which means that Fira Code only sees `<<` followed by `<<<<<`.
