### ISSUE TITLE
Rendering font at 100% is not crisp in VS 2017

### ISSUE THREAD

**Issue by revenger73** [tonsky/FiraCode#455]
In visual studio using the Fira Code font, is not rendering nice at 100%, no matter what font-size is being used.

Using setting 110% results in a nice rendering!

**Comment by tonsky** [comment]
Is it the only font you have this problem with? Do you have same problem with Fira Mono? Whas version of Windows are you on? Do you have clear type enabled? What resolution is your screen? Can you attach screenshots?

**Comment by revenger73** [comment]
Only with FiraCode rendering is not OK, and only at exaxt 100%, see screenshots at 100% and 101%. Changing font-size or font variant has same effect. No issue with default Consolas font, or other fonts. Fira Mono regular has same problem at 100%. No difference between ttf or otf font.

![firacode_100 _vs2017](https://user-images.githubusercontent.com/5694333/28513611-11e6b010-7057-11e7-9d14-cc9dd376221f.png)
![firacode_101 _vs2017](https://user-images.githubusercontent.com/5694333/28513612-11e91152-7057-11e7-8ecf-c6e35aaccc8c.png)

**Comment by revenger73** [comment]
Issue is fixed by enabling Cleartype in Windows!

**Comment by SuTanTank** [comment]
I have ClearType enabled but still not fixed. Set scale level to 99% or 101% fix it.
